Add file size limit
zhelyabuzhsky/yii2-sitemap pull request #21
Opened 2016-12-07 11:34 UTC by PaVeL-Ekt

2016-12-07 16:32 UTC, zhelyabuzhsky requested changes

2016-12-07 16:32 UTC, zhelyabuzhsky commented on src/components/Sitemap.php
> +                    '<sitemap><loc>%s</loc><lastmod>%s</lastmod></sitemap>',
Дак давай как было с отстами и переносами строк, красивей же файл получается

2016-12-07 16:32 UTC, zhelyabuzhsky commented on src/components/Sitemap.php
> +            '<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'
давай всё же сохраним отступ (ну и перенос строк добавь)

2016-12-07 16:32 UTC, zhelyabuzhsky commented on src/components/Sitemap.php
> +        if ($this->maxFileSize > 0 && $fileStat['size'] + strlen($str) > $this->maxFileSize) {
Аналогичная проверка есть в методе create. Надо эту проверку там же сделать.

2016-12-07 16:32 UTC, zhelyabuzhsky commented on src/components/Sitemap.php
> +        $fileSizeAbbr = ['k', 'm', 'g', 't'];
Паша =)))) ты крутой, это факт =)
убери только, пожалуйста, g и t из массива (как ты себе это реально представляешь) и добавь это в документацию как-нибудь прикольно

2016-12-08 07:52 UTC, PaVeL-Ekt commented on src/components/Sitemap.php
> +            '<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'
fix

2016-12-08 07:53 UTC, PaVeL-Ekt commented on src/components/Sitemap.php
> +                    '<sitemap><loc>%s</loc><lastmod>%s</lastmod></sitemap>',
fix

2016-12-08 07:53 UTC, PaVeL-Ekt commented on src/components/Sitemap.php
> +        $fileSizeAbbr = ['k', 'm', 'g', 't'];
fix

2016-12-08 07:53 UTC, PaVeL-Ekt commented on src/components/Sitemap.php
> +        if ($this->maxFileSize > 0 && $fileStat['size'] + strlen($str) > $this->maxFileSize) {
fix

2016-12-08 08:15 UTC, zhelyabuzhsky approved these changes

2016-12-08 08:15 UTC, merged